import { LevelDefinition } from '../types';

export const LEVELS: LevelDefinition[] = [
  {
    id: 1,
    name: 'Training Tower',
    subtitle: 'Learn basic parkour, jumping, wall runs, and ledge pulls',
    theme: 'sunny',
    difficulty: 'Easy',
    height: 52,
    targetTime3Stars: 30,
    targetTime2Stars: 50,
    checkpointsCount: 3,
    totalCoins: 5,
    ambientLight: 0.7,
    directionalLightColor: '#fffbeb',
    skyColorTop: '#38bdf8',
    skyColorBottom: '#bae6fd',
    fogColor: '#93c5fd',
    fogDensity: 0.003,
    description: 'A dedicated athletic obstacle tower designed for honing fundamentals: sprint-jumping, wall running, and ledge grabs.',
  },
  {
    id: 2,
    name: 'Broken City',
    subtitle: 'Crumbling brick rooftops and shattered steel walkways',
    theme: 'sunset',
    difficulty: 'Easy',
    height: 68,
    targetTime3Stars: 42,
    targetTime2Stars: 70,
    checkpointsCount: 3,
    totalCoins: 6,
    ambientLight: 0.6,
    directionalLightColor: '#fb923c',
    skyColorTop: '#f97316',
    skyColorBottom: '#fed7aa',
    fogColor: '#fdba74',
    fogDensity: 0.004,
    description: 'An abandoned urban sector with crumbling ledges and broken steel girders requiring precise leap timings.',
  },
  {
    id: 3,
    name: 'Steel Factory',
    subtitle: 'Industrial catwalks, steam vents, and metal silos',
    theme: 'industrial',
    difficulty: 'Medium',
    height: 80,
    targetTime3Stars: 50,
    targetTime2Stars: 85,
    checkpointsCount: 4,
    totalCoins: 7,
    ambientLight: 0.5,
    directionalLightColor: '#fde047',
    skyColorTop: '#475569',
    skyColorBottom: '#94a3b8',
    fogColor: '#64748b',
    fogDensity: 0.005,
    description: 'Ascend through towering heavy industrial machinery, rotating exhaust vents, and slippery iron grates.',
  },
  {
    id: 4,
    name: 'Skyline',
    subtitle: 'High-rise rooftops and rooftop air conditioning vents',
    theme: 'sunny',
    difficulty: 'Medium',
    height: 95,
    targetTime3Stars: 58,
    targetTime2Stars: 95,
    checkpointsCount: 4,
    totalCoins: 8,
    ambientLight: 0.75,
    directionalLightColor: '#ffffff',
    skyColorTop: '#0284c7',
    skyColorBottom: '#7dd3fc',
    fogColor: '#bae6fd',
    fogDensity: 0.002,
    description: 'Leap across the skyline of modern high-rises. Long gaps require full momentum sprints and timely rolls.',
  },
  {
    id: 5,
    name: 'Construction Site',
    subtitle: 'Hanging concrete slabs, scaffolding, and vertical chutes',
    theme: 'sunset',
    difficulty: 'Medium',
    height: 110,
    targetTime3Stars: 65,
    targetTime2Stars: 110,
    checkpointsCount: 4,
    totalCoins: 8,
    ambientLight: 0.6,
    directionalLightColor: '#f97316',
    skyColorTop: '#ea580c',
    skyColorBottom: '#ffedd5',
    fogColor: '#fed7aa',
    fogDensity: 0.003,
    description: 'Scaffolding reaches toward the clouds. Watch your footing on unbolted planks and shifting cargo crates.',
  },
  {
    id: 6,
    name: 'The Pipes',
    subtitle: 'Narrow high-pressure conduits and vertical balance beams',
    theme: 'fog',
    difficulty: 'Medium',
    height: 125,
    targetTime3Stars: 72,
    targetTime2Stars: 120,
    checkpointsCount: 4,
    totalCoins: 9,
    ambientLight: 0.5,
    directionalLightColor: '#cbd5e1',
    skyColorTop: '#64748b',
    skyColorBottom: '#e2e8f0',
    fogColor: '#94a3b8',
    fogDensity: 0.007,
    description: 'Extreme precision is mandatory. Balance on narrow cylindrical pipes and grab crossbars before falling into the void.',
  },
  {
    id: 7,
    name: 'Highway Tower',
    subtitle: 'Elevated multi-tier highway overpasses suspended in the air',
    theme: 'cloudy',
    difficulty: 'Hard',
    height: 140,
    targetTime3Stars: 80,
    targetTime2Stars: 135,
    checkpointsCount: 5,
    totalCoins: 10,
    ambientLight: 0.65,
    directionalLightColor: '#f8fafc',
    skyColorTop: '#334155',
    skyColorBottom: '#cbd5e1',
    fogColor: '#94a3b8',
    fogDensity: 0.004,
    description: 'Soaring suspension bridges and freeway pillars stacked vertically in an awe-inspiring metropolis.',
  },
  {
    id: 8,
    name: 'The Cranes',
    subtitle: 'Giant yellow construction tower cranes swaying in the wind',
    theme: 'sunset',
    difficulty: 'Hard',
    height: 155,
    targetTime3Stars: 88,
    targetTime2Stars: 145,
    checkpointsCount: 5,
    totalCoins: 10,
    ambientLight: 0.6,
    directionalLightColor: '#f59e0b',
    skyColorTop: '#b45309',
    skyColorBottom: '#fef3c7',
    fogColor: '#fde68a',
    fogDensity: 0.003,
    description: 'Sprint across crane counter-jibs and leap between swinging steel counterweights suspended hundreds of feet high.',
  },
  {
    id: 9,
    name: 'Storm Tower',
    subtitle: 'Thunderstorms, slick metallic floors, and buffeting gusts',
    theme: 'storm',
    difficulty: 'Hard',
    height: 170,
    targetTime3Stars: 95,
    targetTime2Stars: 160,
    checkpointsCount: 5,
    totalCoins: 12,
    ambientLight: 0.4,
    directionalLightColor: '#60a5fa',
    skyColorTop: '#0f172a',
    skyColorBottom: '#1e293b',
    fogColor: '#1e293b',
    fogDensity: 0.006,
    description: 'Heavy rainfall and fierce crosswinds will test your aerial trajectory control and slide timing.',
  },
  {
    id: 10,
    name: 'The Vertical City',
    subtitle: 'Futuristic mega-structure with neon billboards and sky-rail tracks',
    theme: 'cyberpunk',
    difficulty: 'Hard',
    height: 185,
    targetTime3Stars: 105,
    targetTime2Stars: 175,
    checkpointsCount: 5,
    totalCoins: 12,
    ambientLight: 0.45,
    directionalLightColor: '#ec4899',
    skyColorTop: '#090d16',
    skyColorBottom: '#18181b',
    fogColor: '#1e1b4b',
    fogDensity: 0.005,
    description: 'A breathtaking cyberpunk spire lit by holographic ads, magnetic levitation rails, and glowing jump pads.',
  },
  {
    id: 11,
    name: 'Death Climb',
    subtitle: 'Tiny resting platforms and long double-wall run gaps',
    theme: 'night',
    difficulty: 'Hard',
    height: 200,
    targetTime3Stars: 115,
    targetTime2Stars: 190,
    checkpointsCount: 5,
    totalCoins: 12,
    ambientLight: 0.35,
    directionalLightColor: '#38bdf8',
    skyColorTop: '#020617',
    skyColorBottom: '#0f172a',
    fogColor: '#090d16',
    fogDensity: 0.004,
    description: 'A ruthless monolith where one missed jump sends you spiraling hundreds of meters down.',
  },
  {
    id: 12,
    name: 'Red Zone',
    subtitle: 'Laser defense grids and spinning hazard rods',
    theme: 'industrial',
    difficulty: 'Extreme',
    height: 215,
    targetTime3Stars: 120,
    targetTime2Stars: 200,
    checkpointsCount: 6,
    totalCoins: 14,
    ambientLight: 0.4,
    directionalLightColor: '#ef4444',
    skyColorTop: '#450a0a',
    skyColorBottom: '#1c1917',
    fogColor: '#7f1d1d',
    fogDensity: 0.005,
    description: 'Military-grade security grids with pulsing crimson lasers and rapid spinning blocker bars.',
  },
  {
    id: 13,
    name: 'Impossible Tower',
    subtitle: 'Complex moving platforms and disappearing floor plates',
    theme: 'night',
    difficulty: 'Extreme',
    height: 230,
    targetTime3Stars: 130,
    targetTime2Stars: 215,
    checkpointsCount: 6,
    totalCoins: 14,
    ambientLight: 0.4,
    directionalLightColor: '#818cf8',
    skyColorTop: '#0f172a',
    skyColorBottom: '#312e81',
    fogColor: '#1e1b4b',
    fogDensity: 0.004,
    description: 'Timed platforms crumble 1.2 seconds after contact. Memorize the route and maintain breakneck momentum.',
  },
  {
    id: 14,
    name: 'The Endless Rise',
    subtitle: 'Continuous upward wall climbs and high-speed momentum chains',
    theme: 'sunset',
    difficulty: 'Extreme',
    height: 245,
    targetTime3Stars: 140,
    targetTime2Stars: 230,
    checkpointsCount: 6,
    totalCoins: 15,
    ambientLight: 0.55,
    directionalLightColor: '#f97316',
    skyColorTop: '#7c2d12',
    skyColorBottom: '#ffedd5',
    fogColor: '#c2410c',
    fogDensity: 0.003,
    description: 'A spiral ascent demanding consecutive wall runs, 180-degree wall kicks, and blind corner grabs.',
  },
  {
    id: 15,
    name: 'Nightmare Tower',
    subtitle: 'Crushing pistons, electrified metal grates, and wind tunnels',
    theme: 'cyberpunk',
    difficulty: 'Extreme',
    height: 260,
    targetTime3Stars: 150,
    targetTime2Stars: 245,
    checkpointsCount: 6,
    totalCoins: 15,
    ambientLight: 0.35,
    directionalLightColor: '#d946ef',
    skyColorTop: '#1e1b4b',
    skyColorBottom: '#090d16',
    fogColor: '#2e1065',
    fogDensity: 0.005,
    description: 'The ultimate athletic crucible. Master slide-under-lasers and instant recovery rolls on impact.',
  },
  {
    id: 16,
    name: 'Sky Ruins',
    subtitle: 'Ancient stone monolith pillars hovering above cloud layer',
    theme: 'fog',
    difficulty: 'Extreme',
    height: 275,
    targetTime3Stars: 160,
    targetTime2Stars: 260,
    checkpointsCount: 6,
    totalCoins: 16,
    ambientLight: 0.6,
    directionalLightColor: '#f1f5f9',
    skyColorTop: '#475569',
    skyColorBottom: '#f8fafc',
    fogColor: '#cbd5e1',
    fogDensity: 0.006,
    description: 'Ancient monolithic pillars floating in heavy mist. Precision landing on tiny square pillars is key.',
  },
  {
    id: 17,
    name: 'Extreme Heights',
    subtitle: 'Above the troposphere with dizzying vertical camera perspectives',
    theme: 'sunny',
    difficulty: 'Hardcore',
    height: 290,
    targetTime3Stars: 170,
    targetTime2Stars: 280,
    checkpointsCount: 7,
    totalCoins: 16,
    ambientLight: 0.8,
    directionalLightColor: '#ffffff',
    skyColorTop: '#0369a1',
    skyColorBottom: '#e0f2fe',
    fogColor: '#bae6fd',
    fogDensity: 0.002,
    description: 'Thin air, fierce upward thermal drafts, and high-altitude steel arrays that dwarf the world below.',
  },
  {
    id: 18,
    name: 'Final Tower',
    subtitle: 'Comprehensive obstacle gauntlet combining every parkour mechanic',
    theme: 'storm',
    difficulty: 'Hardcore',
    height: 310,
    targetTime3Stars: 185,
    targetTime2Stars: 300,
    checkpointsCount: 7,
    totalCoins: 18,
    ambientLight: 0.45,
    directionalLightColor: '#93c5fd',
    skyColorTop: '#020617',
    skyColorBottom: '#1e293b',
    fogColor: '#172554',
    fogDensity: 0.005,
    description: 'Every mechanic you have learned will be tested: rotating bars, speed slides, wall runs, and swing leaps.',
  },
  {
    id: 19,
    name: 'The Last Climb',
    subtitle: 'Penultimate vertical test of sheer endurance and reflex',
    theme: 'sunset',
    difficulty: 'Hardcore',
    height: 330,
    targetTime3Stars: 200,
    targetTime2Stars: 320,
    checkpointsCount: 7,
    totalCoins: 20,
    ambientLight: 0.55,
    directionalLightColor: '#ea580c',
    skyColorTop: '#9a3412',
    skyColorBottom: '#ffedd5',
    fogColor: '#7c2d12',
    fogDensity: 0.003,
    description: 'A near-vertical skyscraper pinnacle stretching directly into the golden sunset stratosphere.',
  },
  {
    id: 20,
    name: 'THE FINAL SUMMIT',
    subtitle: 'The ultimate vertical ascent to the mythical summit flag',
    theme: 'cyberpunk',
    difficulty: 'Hardcore',
    height: 360,
    targetTime3Stars: 220,
    targetTime2Stars: 350,
    checkpointsCount: 8,
    totalCoins: 25,
    ambientLight: 0.6,
    directionalLightColor: '#fbbf24',
    skyColorTop: '#1e1b4b',
    skyColorBottom: '#fb923c',
    fogColor: '#451a03',
    fogDensity: 0.0025,
    description: 'The legendary pinnacle tower. Ascend through changing weather layers to reach the giant golden Flag at the top of the universe.',
  },
];
